### ISSUE TITLE
File Not Found

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/APCSAReview#5]
Error reported in course Riverside_HS_APCS_A on page index by user kcossa kathryn.cossa@lcps.org
11.2. Objects and Classes
11.2.1. Person Class
11.2.2. Die Class
11.2.3. Coin Class
These sections come up with a File Not Found error when trying to access.

**Comment by bnmnetp** [comment]
Duplicate.  The file has an & in the name, which does not work for web pages.

Fixed
